vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        cursus_files:
            uri_prefix: '%upload%'
            upload_destination: '%kernel.project_dir%/public%upload%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            
    
    
